name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Clojure dependencies
        uses: actions/cache@v4
        with:
          key: clj-${{ github.repository }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: clj-${{ github.repository }}-
          path: |
            ~/.gitlibs
            ~/.m2/repository

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10

      - name: Cache Nix Store
        uses: DeterminateSystems/magic-nix-cache-action@v4

      - name: Deploy release jar
        run: |
          nix develop -c clojure -T:build jar :snapshot false
          nix develop -c clojure -T:build deploy :snapshot false
        env:
          CLOJARS_PASSWORD: ${{secrets.CLOJARS_PASSWORD}}
          CLOJARS_USERNAME: ${{secrets.CLOJARS_USERNAME}}
